import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import nextPlugin from '@next/eslint-plugin-next';

export default tseslint.config(
  {
    // next-env.d.ts is regenerated by Next.js on every dev/build run — never
    // hand-edited, so it's not worth linting (its triple-slash reference is
    // Next's own convention, not something to "fix").
    ignores: ['.next/**', 'node_modules/**', 'next-env.d.ts'],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Only the two long-standing rules-of-hooks rules — not the full v7
    // "React Compiler readiness" ruleset, which adds ~15 new, much stricter
    // rules this codebase was never written against.
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },
  {
    // @next/eslint-plugin-next ships eslintrc-style `configs` only (no flat
    // export yet) — wire the "core-web-vitals" rule set by hand, per Next's
    // own documented flat-config recipe: recommended + the two rules it
    // upgrades to error.
    plugins: { '@next/next': nextPlugin },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      '@next/next/no-html-link-for-pages': 'error',
      '@next/next/no-sync-scripts': 'error',
    },
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      // TypeScript already catches undefined references/globals; the base
      // `no-undef` rule doesn't understand ambient/global TS types and
      // produces false positives (typescript-eslint's own recommendation).
      'no-undef': 'off',
    },
  },
);
