import type { CSSProperties } from "react";

const MONO = "var(--font-mono)";

/** Styles shared by the Context tabs' doc list and drawer. */
export const s = {
  // ---- header: title + badge on the left, filter on the right ----
  topRow: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: 12 } satisfies CSSProperties,
  titleGroup: { display: "flex", alignItems: "center", gap: 10, flex: 1, minWidth: 0 } satisfies CSSProperties,
  filterWrap: { position: "relative", width: 300, maxWidth: "100%" } satisfies CSSProperties,
  filterIcon: {
    position: "absolute",
    left: 10,
    top: "50%",
    transform: "translateY(-50%)",
    color: "var(--text-muted)",
    pointerEvents: "none",
  } satisfies CSSProperties,
  filterInput: {
    width: "100%",
    padding: "7px 10px 7px 32px",
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 13,
  } satisfies CSSProperties,
  subtitle: { margin: "10px 0 16px", fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  code: { fontFamily: MONO, fontSize: 12, color: "var(--text-primary)" } satisfies CSSProperties,

  // ---- rows ----
  list: { display: "flex", flexDirection: "column", gap: 8, listStyle: "none", margin: 0, padding: 0 } satisfies CSSProperties,
  row: (attached: boolean, dragging: boolean, inherited: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    minHeight: 48,
    padding: "8px 12px",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: attached ? "var(--bg-elevated)" : "var(--bg-surface)",
    opacity: dragging ? 0.5 : inherited ? 0.8 : 1,
  }),
  grip: (draggable: boolean): CSSProperties => ({
    flexShrink: 0,
    color: "var(--text-muted)",
    opacity: draggable ? 1 : 0.35,
    cursor: draggable ? "grab" : "default",
  }),
  checkboxCell: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  rowLabel: { display: "flex", alignItems: "baseline", gap: 10, minWidth: 0 } satisfies CSSProperties,
  name: {
    fontFamily: MONO,
    fontSize: 13,
    fontWeight: 500,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  dir: {
    fontFamily: MONO,
    fontSize: 12,
    color: "var(--text-muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    minWidth: 0,
  } satisfies CSSProperties,
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
    border: 0,
  } satisfies CSSProperties,
  tokens: { flexShrink: 0, fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  missing: { flexShrink: 0, fontSize: 12, color: "var(--crit)" } satisfies CSSProperties,
  via: { flexShrink: 0, fontSize: 12, color: "var(--text-secondary)" } satisfies CSSProperties,
  moveSlot: { display: "inline-flex", justifyContent: "flex-end", flexShrink: 0, width: 52 } satisfies CSSProperties,
  moveGroup: (visible: boolean): CSSProperties => ({
    display: "inline-flex",
    gap: 4,
    flexShrink: 0,
    opacity: visible ? 1 : 0,
    transition: "opacity .12s",
  }),
  smallBtn: (disabled: boolean): CSSProperties => ({
    width: 24,
    height: 24,
    display: "inline-grid",
    placeItems: "center",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: disabled ? "not-allowed" : "pointer",
    opacity: disabled ? 0.4 : 1,
    padding: 0,
  }),
  textBtn: {
    flexShrink: 0,
    fontSize: 12,
    padding: "3px 10px",
    borderRadius: 6,
    border: "1px solid var(--border-strong)",
    background: "transparent",
    color: "var(--text-primary)",
    cursor: "pointer",
  } satisfies CSSProperties,
  previewBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    flexShrink: 0,
    minHeight: 28,
    padding: "3px 10px",
    borderRadius: 6,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-surface)",
    color: "var(--text-secondary)",
    fontSize: 12.5,
    cursor: "pointer",
  } satisfies CSSProperties,
  message: { fontSize: 13, color: "var(--text-secondary)", padding: "12px 0" } satisfies CSSProperties,

  // ---- drawer ----
  drawerTitle: { display: "flex", alignItems: "center", gap: 10, minWidth: 0 } satisfies CSSProperties,
  drawerTitleIcon: { flexShrink: 0, color: "var(--accent-text)" } satisfies CSSProperties,
  drawerPath: { fontFamily: MONO, fontSize: 15, fontWeight: 500, overflowWrap: "anywhere" } satisfies CSSProperties,
  drawerMeta: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 16,
    marginTop: 6,
    paddingLeft: 28,
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  drawerMetaItem: { display: "inline-flex", alignItems: "center", gap: 6 } satisfies CSSProperties,
  drawerTokens: { fontFamily: MONO, fontSize: 12.5 } satisfies CSSProperties,
  attachedToggle: (on: boolean): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    minHeight: 32,
    padding: "6px 14px",
    marginBottom: 16,
    borderRadius: 7,
    border: `1px solid ${on ? "var(--border-strong)" : "var(--border)"}`,
    background: on ? "var(--bg-elevated)" : "transparent",
    color: on ? "var(--text-primary)" : "var(--text-secondary)",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
  }),
  drawerCard: {
    padding: "22px 24px",
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-primary)",
    fontSize: 14,
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
};
