import type { CSSProperties } from "react";

/** Styles for the Project Context page. */
export const s = {
  page: { padding: "28px 32px", maxWidth: 1200, margin: "0 auto" } satisfies CSSProperties,
  headerRow: { display: "flex", alignItems: "center", gap: 16, marginBottom: 16 } satisfies CSSProperties,
  heading: { fontSize: 26, fontWeight: 700, flex: 1 } satisfies CSSProperties,
  layout: {
    display: "grid",
    gridTemplateColumns: "minmax(240px, 320px) 1fr",
    gap: 16,
    alignItems: "start",
  } satisfies CSSProperties,
  panel: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: 12,
    minWidth: 0,
  } satisfies CSSProperties,
  footer: { fontSize: 12, color: "var(--text-muted)", marginTop: 12 } satisfies CSSProperties,
  message: { fontSize: 14, color: "var(--text-secondary)", padding: "24px 0" } satisfies CSSProperties,

  // ---- tree ----
  treeList: { listStyle: "none", margin: 0, padding: 0 } satisfies CSSProperties,
  folderRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: "var(--text-muted)",
    padding: "6px 4px",
  } satisfies CSSProperties,
  nested: { listStyle: "none", margin: 0, paddingLeft: 14 } satisfies CSSProperties,
  fileButton: (active: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 2,
    width: "100%",
    textAlign: "left",
    padding: "6px 8px",
    borderRadius: 6,
    border: "none",
    cursor: "pointer",
    fontSize: 13,
    color: "var(--text-primary)",
    background: active ? "var(--bg-hover)" : "transparent",
  }),
  fileMeta: { fontSize: 11, color: "var(--text-muted)" } satisfies CSSProperties,
  localEdit: { fontSize: 11, color: "var(--text-secondary)" } satisfies CSSProperties,

  // ---- preview ----
  breadcrumb: {
    display: "flex",
    flexWrap: "wrap",
    gap: 4,
    fontSize: 12,
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  breadcrumbLast: { color: "var(--text-primary)", fontWeight: 600 } satisfies CSSProperties,
  metaRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
    fontSize: 12,
    color: "var(--text-secondary)",
    marginBottom: 12,
  } satisfies CSSProperties,
  toggleGroup: { display: "inline-flex", gap: 4, marginLeft: "auto" } satisfies CSSProperties,
  toggleButton: (active: boolean, disabled: boolean): CSSProperties => ({
    padding: "4px 10px",
    fontSize: 12,
    borderRadius: 6,
    border: "1px solid var(--border)",
    cursor: disabled ? "not-allowed" : "pointer",
    opacity: disabled ? 0.5 : 1,
    color: "var(--text-primary)",
    background: active ? "var(--bg-hover)" : "transparent",
  }),
  body: { fontSize: 14, overflowWrap: "anywhere" } satisfies CSSProperties,
  editorLabel: { display: "block" } satisfies CSSProperties,
  editorCaption: { display: "block", fontSize: 12, color: "var(--text-muted)", marginBottom: 6 } satisfies CSSProperties,
  editorActions: { display: "flex", alignItems: "center", gap: 12, marginTop: 10 } satisfies CSSProperties,
  editorError: { fontSize: 13, color: "var(--crit)" } satisfies CSSProperties,
  dialogBody: { padding: "16px 24px", fontSize: 13 } satisfies CSSProperties,
  dialogActions: { display: "flex", justifyContent: "flex-end", gap: 8 } satisfies CSSProperties,
  skeletonCol: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
};
