import type { CSSProperties } from "react";

const MONO = "var(--font-mono)";

/** Styles for the Project Context page: a file panel on the left, the document on the right. */
export const s = {
  page: {
    display: "grid",
    gridTemplateColumns: "minmax(220px, 260px) 1fr",
    height: "100%",
    minHeight: 0,
  } satisfies CSSProperties,

  // ---- left: file panel ----
  sidebar: {
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    minWidth: 0,
    borderRight: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  sidebarHeader: { padding: "18px 16px 10px" } satisfies CSSProperties,
  eyebrow: {
    margin: 0,
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  roots: {
    marginTop: 4,
    fontFamily: MONO,
    fontSize: 12,
    color: "var(--text-secondary)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  toolbar: { display: "flex", gap: 4, padding: "0 10px 8px" } satisfies CSSProperties,
  treeScroll: { flex: 1, minHeight: 0, overflow: "auto", padding: "0 8px 12px" } satisfies CSSProperties,
  sidebarFooter: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "12px 16px",
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  footerDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "var(--ok)",
    flexShrink: 0,
  } satisfies CSSProperties,
  skeletonCol: { display: "flex", flexDirection: "column", gap: 6, padding: "4px 8px" } satisfies CSSProperties,

  // ---- tree ----
  treeList: { listStyle: "none", margin: 0, padding: 0 } satisfies CSSProperties,
  nested: { listStyle: "none", margin: 0, paddingLeft: 12 } satisfies CSSProperties,
  folderButton: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    width: "100%",
    minHeight: 28,
    padding: "4px 8px",
    border: "none",
    borderRadius: 6,
    background: "transparent",
    cursor: "pointer",
    textAlign: "left",
    fontFamily: MONO,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  fileButton: (active: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 2,
    width: "100%",
    minHeight: 30,
    padding: "6px 8px",
    border: "none",
    borderRadius: 6,
    background: active ? "var(--bg-hover)" : "transparent",
    cursor: "pointer",
    textAlign: "left",
    color: active ? "var(--text-primary)" : "var(--text-secondary)",
  }),
  fileLine: { display: "flex", alignItems: "center", gap: 8, width: "100%", minWidth: 0 } satisfies CSSProperties,
  fileIcon: (active: boolean): CSSProperties => ({
    flexShrink: 0,
    color: active ? "var(--accent-text)" : "var(--text-muted)",
  }),
  fileName: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontFamily: MONO,
    fontSize: 13,
  } satisfies CSSProperties,
  fileTokens: { flexShrink: 0, fontSize: 11, color: "var(--text-muted)" } satisfies CSSProperties,
  rowLocalEdit: { paddingLeft: 22, fontSize: 11, color: "var(--warn)" } satisfies CSSProperties,

  // ---- right: document ----
  main: { display: "flex", flexDirection: "column", minWidth: 0, minHeight: 0 } satisfies CSSProperties,
  docHeader: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
    minHeight: 56,
    padding: "10px 28px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  breadcrumb: {
    display: "flex",
    alignItems: "center",
    minWidth: 0,
    fontFamily: MONO,
    fontSize: 13,
    color: "var(--text-muted)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  breadcrumbLast: { color: "var(--text-primary)", fontWeight: 500 } satisfies CSSProperties,
  segmented: {
    display: "inline-flex",
    padding: 2,
    gap: 2,
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  segment: (active: boolean): CSSProperties => ({
    minHeight: 24,
    padding: "3px 12px",
    border: "none",
    borderRadius: 5,
    cursor: "pointer",
    fontSize: 12,
    fontWeight: active ? 600 : 500,
    color: active ? "var(--text-primary)" : "var(--text-muted)",
    background: active ? "var(--bg-hover)" : "transparent",
  }),
  docMeta: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
    marginLeft: "auto",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  metaItem: { display: "inline-flex", alignItems: "center", gap: 6 } satisfies CSSProperties,
  headerLocalEdit: { fontSize: 12, color: "var(--warn)" } satisfies CSSProperties,
  docScroll: { flex: 1, minHeight: 0, overflow: "auto", padding: "24px 28px 40px" } satisfies CSSProperties,
  body: { maxWidth: 760, fontSize: 14, overflowWrap: "anywhere" } satisfies CSSProperties,
  centered: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  } satisfies CSSProperties,
  message: { fontSize: 14, color: "var(--text-secondary)", textAlign: "center", maxWidth: 420 } satisfies CSSProperties,

  // ---- editor ----
  editorLabel: { display: "block", maxWidth: 900 } satisfies CSSProperties,
  editorCaption: { display: "block", fontSize: 12, color: "var(--text-muted)", marginBottom: 6 } satisfies CSSProperties,
  editorActions: { display: "flex", alignItems: "center", gap: 12, marginTop: 10 } satisfies CSSProperties,
  editorError: { fontSize: 13, color: "var(--crit)" } satisfies CSSProperties,
  dialogBody: { padding: "16px 24px", fontSize: 13 } satisfies CSSProperties,
  dialogActions: { display: "flex", justifyContent: "flex-end", gap: 8 } satisfies CSSProperties,
};
